name: ONM Integration Tests

on: push

jobs:
  Ubuntu:
    name: Test OMF on Ubuntu
    runs-on: ubuntu-18.04
    timeout-minutes: 120
    env: 
      GUROBI_LICENSE: ${{ secrets.GUROBI_LICENSE }}
    steps:
      - uses: actions/checkout@v2 # Checkout whichever ref that triggered this workflow
      - name: Install Dependencies
        run: sudo apt install python3
      - name: Add license
        run: sudo mkdir /opt/gurobi && sudo echo "$GUROBI_LICENSE" >> /opt/gurobi/gurobi.lic
      - name: Run Tests
        run: sudo python3 __init__.py
  macOS:
    name: Test on macOS
    runs-on: macos-latest
    env: 
      GUROBI_LICENSE: ${{ secrets.GUROBI_LICENSE }}
      TEST: ${{ secrets.TEST}}
    steps:
     - uses: actions/checkout@v2
     - name: Install dependencies
       run: brew link --overwrite python@3.8
     - name: test secret
       run: echo "$TEST" >> ~/test
       run: echo ~/test
     - name: Add license
       run: echo "$GUROBI_LICENSE" >> ~/gurobi.lic
     - name: Run tests
       run: sudo python3 __init__.py
